In [1]:
import math
    

In [2]:
def basic_sigmoid(x):
    s = 1/(1+math.exp(-x))
    return s

In [3]:
basic_sigmoid(-1)

0.2689414213699951

In [4]:
import numpy as np

# result of np.exp
x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [5]:
# ex of vector operation 
x = np.array([1,2,3])
print(x+3)

[4 5 6]


In [6]:
def sigmoid(x):

    s = 1/(1+np.exp(-x))
    return s

In [7]:
x = sigmoid(np.array([1,2,3]))
x

array([0.73105858, 0.88079708, 0.95257413])

In [8]:
def d_sigmoid(x):

    s = 1/(1+np.exp(-x))
    d = s * (1 - s) 
    return d

In [9]:
x = d_sigmoid(np.array([1,2,3]))
x

array([0.19661193, 0.10499359, 0.04517666])

In [10]:
image = np.random.rand(3,3,2)
image

array([[[0.26769038, 0.55162328],
        [0.70341737, 0.98727198],
        [0.31114157, 0.91220441]],

       [[0.2863873 , 0.78027053],
        [0.05768992, 0.75989942],
        [0.65361434, 0.90415828]],

       [[0.3970924 , 0.18478497],
        [0.17290836, 0.52553674],
        [0.36484641, 0.8146151 ]]])

In [11]:
def dem_reshape(img):
    img = img.reshape(img.shape[0]*img.shape[1],img.shape[2])
    return img

In [12]:
image = dem_reshape(image)
image

array([[0.26769038, 0.55162328],
       [0.70341737, 0.98727198],
       [0.31114157, 0.91220441],
       [0.2863873 , 0.78027053],
       [0.05768992, 0.75989942],
       [0.65361434, 0.90415828],
       [0.3970924 , 0.18478497],
       [0.17290836, 0.52553674],
       [0.36484641, 0.8146151 ]])

In [13]:
def normalizerows(img):
    x_norm = np.linalg.norm(img,axis = 1, keepdims = True)
    img = img/x_norm
    return img

image = normalizerows(image)
image

array([[0.43658601, 0.89966252],
       [0.58026717, 0.81442618],
       [0.32282525, 0.94645859],
       [0.34456018, 0.93876423],
       [0.0757    , 0.99713064],
       [0.5858505 , 0.81041915],
       [0.90664179, 0.42190125],
       [0.31253175, 0.94990731],
       [0.40875187, 0.91264555]])

In [14]:
img1 = np.array([
    [0,1000,4],
    [2,6,4]])
img1 = normalizerows(img1)
img1

array([[0.        , 0.999992  , 0.00399997],
       [0.26726124, 0.80178373, 0.53452248]])

In [19]:
def softmax(x):
    x_exp = np.exp(x)

    x_sum = np.sum(x_exp, axis = 1 , keepdims = True)

    x = x_exp/x_sum

    return x

img2 = np.array([[9,2,5,0,0],
                 [7,5,0,0,0]])

img2  = softmax(img2)
img2

array([[9.80897665e-01, 8.94462891e-04, 1.79657674e-02, 1.21052389e-04,
        1.21052389e-04],
       [8.78679856e-01, 1.18916387e-01, 8.01252314e-04, 8.01252314e-04,
        8.01252314e-04]])

In [25]:
import time

x1 = np.random.rand(10000000)
x2 = np.random.rand(10000000)

tic = (time.process_time())
dot = 0
for i in range(len(x1)):
    dot += x1[i]*x2[i]
toc = time.process_time()
print("dot  = " +str(dot)+"\n------Computationtime--------" + str(1000*(toc-tic))+"ms")

dot  = 2499843.4046221836
------Computationtime--------3296.875ms


In [26]:
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot  = " +str(dot)+"\n------Computationtime--------" + str(1000*(toc-tic))+"ms")

dot  = 2499843.404622003
------Computationtime--------31.25ms
